package jp.ohwada.android.notofont;

/**
 * Constant
 */
public class Constant {

    public final static boolean DEBUG = true;
	public final static String TAG = "NoteFont";

	public final static String[] DOWNLOAD_NAMES = {
		"NotoSans-unhinted.zip",
		"NotoSerif-unhinted.zip",
		"NotoSansGothic-unhinted.zip",
		"NotoSansJapanese-hinted.zip",
		"NotoNaskhArabic-unhinted.zip",
		"NotoKufiArabic-unhinted.zip",
		"NotoSerifArmenian-unhinted.zip",
		"NotoSansArmenian-unhinted.zip",
		"NotoSansAvestan-unhinted.zip",
		"NotoSansAvestan-unhinted.zip",
		"NotoSansBalinese-unhinted.zip",
		"NotoSansBamum-unhinted.zip",
		"NotoSansBatak-unhinted.zip",
		"NotoSansBengali-unhinted.zip",
		"NotoSansBrahmi-unhinted.zip",
		"NotoSansBuginese-unhinted.zip",
		"NotoSansBuhid-unhinted.zip",
		"NotoSansCanadianAboriginal-unhinted.zip",
		"NotoSansCarian-unhinted.zip",
		"NotoSansCham-unhinted.zip",
		"NotoSansCherokee-unhinted.zip",
		"NotoSansCoptic-unhinted.zip",
		"NotoSansCypriot-unhinted.zip",
		"NotoSansDeseret-unhinted.zip",
		"NotoSansDevanagari-unhinted.zip",
		"NotoSansEgyptianHieroglyphs-unhinted.zip",
		"NotoSansEthiopic-unhinted.zip",
		"NotoSansGeorgian-unhinted.zip",
		"NotoSerifGeorgian-unhinted.zip",
		"NotoSansGlagolitic-unhinted.zip",
		"NotoSansGothic-unhinted.zip",
		"NotoSansGujarati-unhinted.zip",
		"NotoSansGurmukhi-unhinted.zip",
		"NotoSansHanunoo-unhinted.zip",
		"NotoSansHebrew-unhinted.zip",
		"NotoSansImperialAramaic-unhinted.zip",
		"NotoSansInscriptionalPahlavi-unhinted.zip",
		"NotoSansInscriptionalParthian-unhinted.zip",
		"NotoSansJapanese-hinted.zip",
		"NotoSansJavanese-unhinted.zip",
		"NotoSansKaithi-unhinted.zip",
		"NotoSansKannada-unhinted.zip",
		"NotoSansKayahLi-unhinted.zip",
		"NotoSansKharoshthi-unhinted.zip",
		"NotoSerifKhmer-unhinted.zip",
		"NotoSansKhmer-unhinted.zip",
		"NotoSansKorean-hinted.zip",
		"NotoSansLao-unhinted.zip",
		"NotoSerifLao-unhinted.zip",
		"NotoSansLepcha-unhinted.zip",
		"NotoSansLimbu-unhinted.zip",
		"NotoSansLinearB-unhinted.zip",
		"NotoSansLisu-unhinted.zip",
		"NotoSansLycian-unhinted.zip",
		"NotoSansLydian-unhinted.zip",
		"NotoSansMalayalam-unhinted.zip",
		"NotoSansMandaic-unhinted.zip",
		"NotoSansMeeteiMayek-unhinted.zip",
		"NotoSansMongolian-unhinted.zip",
		"NotoSansMyanmar-unhinted.zip",
		"NotoSansNewTaiLue-unhinted.zip",
		"NotoSansNKo-unhinted.zip",
		"NotoSansOgham-unhinted.zip",
		"NotoSansOlChiki-unhinted.zip",
		"NotoSansOldItalic-unhinted.zip",
		"NotoSansOldPersian-unhinted.zip",
		"NotoSansOldSouthArabian-unhinted.zip",
		"NotoSansOldTurkic-unhinted.zip",
		"NotoSansOsmanya-unhinted.zip",
		"NotoSansPhags-pa-unhinted.zip",
		"NotoSansPhoenician-unhinted.zip",
		"NotoSansRejang-unhinted.zip",
		"NotoSansRunic-unhinted.zip",
		"NotoSansSChinese-hinted.zip",
		"NotoSansSamaritan-unhinted.zip",
		"NotoSansSaurashtra-unhinted.zip",
		"NotoSansShavian-unhinted.zip",
		"NotoSansSinhala-unhinted.zip",
		"NotoSansSumero-AkkadianCuneiform-unhinted.zip",
		"NotoSansSundanese-unhinted.zip",
		"NotoSansSylotiNagri-unhinted.zip",
		"NotoSansSymbols-unhinted.zip",
		"NotoSansSyriacEastern-unhinted.zip",
		"NotoSansSyriacEstrangela-unhinted.zip",
		"NotoSansSyriacWestern-unhinted.zip",
		"NotoSansTChinese-hinted.zip",
		"NotoSansTagalog-unhinted.zip",
		"NotoSansTagbanwa-unhinted.zip",
		"NotoSansTaiLe-unhinted.zip",
		"NotoSansTaiTham-unhinted.zip",
		"NotoSansTaiViet-unhinted.zip",
		"NotoSansTamil-unhinted.zip",
		"NotoSansTelugu-unhinted.zip",
		"NotoSansThai-unhinted.zip",
		"NotoSerifThai-unhinted.zip",
		"NotoSansTifinagh-unhinted.zip",
		"NotoSansUgaritic-unhinted.zip",
		"NotoSansVai-unhinted.zip",
		"NotoSansYi-unhinted.zip" };

}
